script: Properly handle messaging errors in `components/constellation/constellation.rs` (#41419)
Fix panic on background_monitor_hang send, allowing graceful cleanups.

Url example
`https://cosihome.com/products/cooling-blanket/luxury-cooling-blanket-multi-season-lightweight-soft/`
- causes many redirects.

```
thread 'Script#4' panicked at /app/third_party/servo/components/script/dom/history.rs:357:24:
Unknown top-level browsing context`
thread 'Script#5' panicked at /app/third_party/servo/components/background_hang_monitor/background_hang_monitor.rs:138:14
```

---------

Signed-off-by: j-mendez <jeff@spider.cloud>