ohos: Add target ohos to the hitrace feature guards to address clippy warnings (#46861)
when doing `cargo clippy --all-targets --all-features` we currently have
several different warning, and one of them is ohos related,
because the `hitrace` crate has some functions like `start_trace_ex` be
guarded with `target_env = "ohos"`, but on the servo side, we only
checked for the `feature = "tracing-hitrace"`, so it resulted in

```
error[E0425]: cannot find function `start_trace_ex` in crate `hitrace`
   --> ports/servoshell/lib.rs:284:26
    |
284 |                 hitrace::start_trace_ex(
```

this PR adds the `target_env = "ohos"` in the servo side, and thus gets
rid of the clippy warning

Testing: there are no tests

Signed-off-by: Asset Malik <5373400+janeoa@users.noreply.github.com>