build: bump jiff from 0.2.32 to 0.2.34 (#46675)
Bumps [jiff](https://github.com/BurntSushi/jiff) from 0.2.32 to 0.2.34.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/BurntSushi/jiff/blob/master/CHANGELOG.md">jiff's
changelog</a>.</em></p>
<blockquote>
<h1>0.2.34 (2026-07-19)</h1>
<p>This release contains a few small enhancements. Namely, some error
messages
for parsing datetime values have been improved by removing some
redundant
messaging. Additionally, the <code>strftime</code> APIs on datetime
values can no longer
panic. Instead, they'll silently pass through invalid formatting
directives.</p>
<p>Enhancements:</p>
<ul>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/519">#519</a>:
Improve some parsing error messages by removing redundancy.</li>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/585">#585</a>:
Change <code>Timestamp::strftime</code> (and similar methods) so that
they will never
panic.</li>
</ul>
<h1>0.2.33 (2026-07-18)</h1>
<p>This release permits the use of a global time zone database in
<code>alloc</code>-only
environments. It also contains a massive internal refactor that
introduces a
new <code>jiff-core</code> crate for better code sharing.</p>
<p>Enhancements:</p>
<ul>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/285">#285</a>:
Decouple naming of time zones from their TZif data.</li>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/373">#373</a>:
Add a new <code>jiff-core</code> crate for better code sharing.</li>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/533">#533</a>:
A bundled <code>TimeZoneDatabase</code> is now available when only
<code>alloc</code> is enabled.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/BurntSushi/jiff/commit/7311a6ac67cf9f3ddada489feb634575b3607d8f"><code>7311a6a</code></a>
0.2.34</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/5682809f7bc4edf049ca53f8e70f5df1c70fe80c"><code>5682809</code></a>
test: fixes for testing from released crates</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/cebda72f8f7702ac618e5a54ac844d0853c89de7"><code>cebda72</code></a>
cargo: switch to a virtual manifest</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/21be3de9eb993f844fceaf6ed54b74d851338378"><code>21be3de</code></a>
util: remove vestigial bounds error wrapper</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/1f9cf9ed561e930c0e5bf358f1e332b6dc196586"><code>1f9cf9e</code></a>
error: tighten up some error messages</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/afc23a269faadff5fb19bd91f42977db489fb73e"><code>afc23a2</code></a>
fmt: use lenient formatting mode for <code>strftime</code> APIs</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/ddd26a89c7f0a6fa8008f35021462e71a8db8b40"><code>ddd26a8</code></a>
0.2.33</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/4c480d99f61a28768e3610040ca8d6aae97e260f"><code>4c480d9</code></a>
scripts: allow unbound variables</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/496428e2fd78d770415e9c6bdf56aa670642b59d"><code>496428e</code></a>
ci: clarify comment about ranged integers</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/c0b0d4b9273153093660bdb22da228879283ddcb"><code>c0b0d4b</code></a>
tz: remove TZif name <code>jiff_core::tz::tzif::TimeZone</code></li>
<li>Additional commits viewable in <a
href="https://github.com/BurntSushi/jiff/compare/jiff-static-0.2.32...jiff-static-0.2.34">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=jiff&package-manager=cargo&previous-version=0.2.32&new-version=0.2.34)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>