Fix build failure with tracing feature (#35009)
* Fix build failure with tracing feature

Skip tracing preferences for now to avoid:
```
error[E0277]: `Preferences` doesn't implement `std::fmt::Debug`
```

Signed-off-by: Jonathan Schwender <schwenderjonathan@gmail.com>

* Fix warning about unused tracing span.

The tracing span is "used" when it is dropped,
so in that sense it is a false positive.

Signed-off-by: Jonathan Schwender <schwenderjonathan@gmail.com>

---------

Signed-off-by: Jonathan Schwender <schwenderjonathan@gmail.com>