build: bump jiff from 0.2.18 to 0.2.19 (#42381)
Bumps [jiff](https://github.com/BurntSushi/jiff) from 0.2.18 to 0.2.19.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/BurntSushi/jiff/blob/master/CHANGELOG.md">jiff's
changelog</a>.</em></p>
<blockquote>
<h1>0.2.19 (2026-02-05)</h1>
<p>This is a small release with a performance optimization (with respect
to doing
heavily contended arithmetic on <code>Zoned</code> values) and a bug fix
for a panic
that can occur when using <code>%2s</code> in <code>strftime</code>.</p>
<p>Enhancements:</p>
<ul>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/491">#491</a>:
Avoid cloning <code>TimeZone</code> for consuming operations on
<code>Zoned</code>.</li>
</ul>
<p>Bug fixes:</p>
<ul>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/497">#497</a>:
Fix a panic in <code>timestamp.strftime(&quot;%2s&quot;)</code>.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/BurntSushi/jiff/commit/52b2b0fcf6e165807c1354f70cae30cf6550c97c"><code>52b2b0f</code></a>
0.2.19</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/ef47ecc17f7fc6b068f9d7032c93956c269748ae"><code>ef47ecc</code></a>
changelog: 0.2.19</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/196442da646b268d54ecfa14f561d47f69d9a978"><code>196442d</code></a>
fmt: fix panic in <code>strftime</code> for <code>%2s</code></li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/3c9ba667390a1f3aeb104fb9110475defa609bb0"><code>3c9ba66</code></a>
zoned: kinda optimize <code>Zoned::default()</code></li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/4c9c982269fd69abd08afd84c42b15639a9bd114"><code>4c9c982</code></a>
ci: fix emscripten build</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/d41b397367611ee27fad04c6f83ec50972632425"><code>d41b397</code></a>
zoned: optimize <code>Zoned::{add,sub,add_assign,sub_assign}</code> when
<code>Zoned</code> is cons...</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/66ba0fe164c91082d63bb2687c41629bb125bd26"><code>66ba0fe</code></a>
fmt: rip ranged integers out of Temporal RFC 9557 parser</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/a651ac732666cd4ebe0a5dbc2b5dcde0088632cf"><code>a651ac7</code></a>
error: update <code>Error::is_range</code> predicate</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/c2dcbca9f8a2619e130581d5b787c6de9a3e55e2"><code>c2dcbca</code></a>
fmt: refactor Temporal parser to get rid of input capture</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/d439a66e87e3e62e5b6ca4d86a5353fd5a500b9c"><code>d439a66</code></a>
fmt: rename <code>strtime::format</code> to
<code>strtime::print</code></li>
<li>Additional commits viewable in <a
href="https://github.com/BurntSushi/jiff/compare/jiff-static-0.2.18...jiff-static-0.2.19">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=jiff&package-manager=cargo&previous-version=0.2.18&new-version=0.2.19)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>